services:
  - type: web
    name: mr-dough-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    env:
      - key: MONGODB_URI
        value: ${MONGODB_URI}
      - key: JWT_SECRET
        value: ${JWT_SECRET}
      - key: ADMIN_EMAIL
        value: ${ADMIN_EMAIL}
      - key: ADMIN_PASSWORD
        value: ${ADMIN_PASSWORD}
      - key: CLOUDINARY_CLOUD_NAME
        value: ${CLOUDINARY_CLOUD_NAME}
      - key: CLOUDINARY_API_KEY
        value: ${CLOUDINARY_API_KEY}
      - key: CLOUDINARY_API_SECRET
        value: ${CLOUDINARY_API_SECRET}
      - key: TELEGRAM_BOT_TOKEN
        value: ${TELEGRAM_BOT_TOKEN}
      - key: OWNER_CHAT_ID
        value: ${OWNER_CHAT_ID}
      - key: FRONTEND_URL
        value: https://mr-dough-web.netlify.app